electronics_calculator_1_4: main.o Current.o Power.o Print.o
					    g++ main.o Current.o Power.o Print.o -o electronics_calculator_1_4

main.o: main.cpp
		g++ -c main.cpp

Current.o: Current.cpp
		g++ -c Current.cpp

Power.o: Power.cpp
		g++ -c Power.cpp

Print.o: Print.cpp	
		g++ -c Print.cpp